### ISSUE TITLE
Crash com.android.phone on boot completed

### ISSUE THREAD

**Issue by PycmShoma** [crdroidandroid/android_packages_services_Telephony#3]
Process: com.android.phone
PID: 2866
UID: 1001
Flags: 0x38c83e4d
Package: com.android.providers.telephony v32 (12)
Package: com.qti.qualcomm.datastatusnotification v30 (11)
Package: com.android.ons v32 (12)
Package: com.android.phone v32 (12)
Foreground: No
Process-Runtime: 24881
Build: Xiaomi/cepheus/cepheus:12/SQ3A.220705.003.A1/1659728653:user/release-keys
Loading-Progress: 1.0

java.lang.NoSuchMethodError: No virtual method isDataAllowedInVoiceCall()Z in class Landroid/telephony/TelephonyManager; or its super classes (declaration of 'android.telephony.TelephonyManager' appears in /system/framework/framework.jar!classes3.dex)
	at com.qti.qualcomm.datastatusnotification.DataStatusNotificationService.updateDataStatus(DataStatusNotificationService.java:591)
	at com.qti.qualcomm.datastatusnotification.DataStatusNotificationService.access$1400(DataStatusNotificationService.java:38)
	at com.qti.qualcomm.datastatusnotification.DataStatusNotificationService$3.onCallStateChanged(DataStatusNotificationService.java:558)
	at android.telephony.PhoneStateListener$IPhoneStateListenerStub.lambda$onLegacyCallStateChanged$10(PhoneStateListener.java:1391)
	at android.telephony.PhoneStateListener$IPhoneStateListenerStub$$ExternalSyntheticLambda42.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by neobuddy89** [comment]
Delete  com.qti.qualcomm.datastatusnotification package or update from Android 12.
